-- CreateTable
CREATE TABLE "public"."Task_DB" (
    "id" SERIAL NOT NULL,
    "orderCo" DOUBLE PRECISION,
    "orTy" TEXT,
    "orderNumber" DOUBLE PRECISION,
    "branchPlant" TEXT,
    "customerPO" TEXT,
    "suburbTown" TEXT,
    "name" TEXT,
    "description" TEXT,
    "quantityShipped" DOUBLE PRECISION,
    "itemNumber" DOUBLE PRECISION,
    "postalCode" DOUBLE PRECISION,
    "revNbr" DOUBLE PRECISION,
    "revisionReason" TEXT,
    "routeCode" TEXT,
    "schedPick" TIMESTAMP(3),
    "truckId" TEXT,
    "location" TEXT,
    "scheduledPickTime" DOUBLE PRECISION,
    "requestDate" TIMESTAMP(3),
    "soldTo" DOUBLE PRECISION,
    "shipTo" DOUBLE PRECISION,
    "deliverTo" DOUBLE PRECISION,
    "stateCode" TEXT,
    "lnTy" TEXT,
    "descriptionLine2" TEXT,
    "zoneNo" TEXT,
    "stopCode" TEXT,
    "nextStat" DOUBLE PRECISION,
    "lastStat" DOUBLE PRECISION,
    "priority" DOUBLE PRECISION,
    "futureQtyCommitted" DOUBLE PRECISION,
    "quantityOrdered" DOUBLE PRECISION,
    "reasonCode" TEXT,
    "lineNumber" DOUBLE PRECISION,

    CONSTRAINT "Task_DB_pkey" PRIMARY KEY ("id")
);
